"""added foreign kyey job application to resume table

Revision ID: bfb81442210e
Revises: e376b00f4139
Create Date: 2025-05-13 14:11:34.138311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb81442210e'
down_revision: Union[str, None] = 'e376b00f4139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('job_application_id', sa.UUID(), nullable=True))
    op.drop_constraint('resume_job_post_id_fkey', 'resume', type_='foreignkey')
    op.create_foreign_key(None, 'resume', 'job_application', ['job_application_id'], ['id'])
    op.drop_column('resume', 'job_post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('job_post_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.create_foreign_key('resume_job_post_id_fkey', 'resume', 'job_post', ['job_post_id'], ['id'])
    op.drop_column('resume', 'job_application_id')
    # ### end Alembic commands ###
