"""update relatioonship of resume with applied job

Revision ID: e376b00f4139
Revises: f8ac1ad3af53
Create Date: 2025-05-13 13:54:13.166954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e376b00f4139'
down_revision: Union[str, None] = 'f8ac1ad3af53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('job_post_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'resume', 'job_post', ['job_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='foreignkey')
    op.drop_column('resume', 'job_post_id')
    # ### end Alembic commands ###
